apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wm3lbnuao-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wm3lbnuao-java-quarkus-gitops